### ISSUE TITLE
Txt den kullanıcı takip listesi çekme

### ISSUE THREAD

**Issue by serhatavcu** [mustafadalga/Instagram-Bot#1]
Merhaba, öncelikle kusursuz çalışıyor emeğiniz için teşekkür ederim.
bildiğiniz gibi takipçi arttrımak için instagramda takip ve takipten çıkma büyük ihtiyaç program başarılı şekilde takip ediyor ama her kullanıcı adını tek tek girmek gerekli bunu otomatikleştirebilir miyiz
a- şu kullanıcının takipçilerini takip et şu random zaman aralığında takip etsin örneğin 2 ile 3 dk arası
b- txt den takip edilecek kullanıcı adlarını çekip şu random zaman aralığında takip etsin örneğin 2 ile 3 dk arası

bu iki seçenekten biri modül olarak eklenirse süper olur
tekrar elinize sağlık böyle konuda Türkçe içerik ve geliştirici bulmak memnun etti
başarılar

**Comment by mustafadalga** [comment]
Merhaba  @serquat , değerli yorumlarınız ve önerileriniz için teşekkür ederim.
Önerileriniz olan , bir kullanıcının  takipçilerini  veya txt dosyasından alınan kullanıcı adlarını rastgele olarak takip etme seçeneklerinizi geliştirebiliriz.

Şuan Javascript ile oyun geliştirme üzerine çalıştığım için Python üzerinde çalışmaya vakit bulamadım.Müsait bir zamanda önerilerinizi geliştirmeye çalışacağım.

**Comment by mustafadalga** [comment]
Merhaba @serquat ,
[Instagram Bot](https://github.com/mustafadalga/Instagram-Bot)'unun yeni versiyonu yayınlanmıştır.
