### ISSUE TITLE
Kodriver hatasi

### ISSUE THREAD

**Issue by kgdsa** [mustafadalga/Instagram-Bot#11]
Merhabalar her şeyi yaptım fakat calistirdigimda Kodriver hatası alıyorum.Yardım eder misin?

**Comment by mustafadalga** [comment]
Merhaba ,hata mesajını paylaşır mısınız ?

**Comment by mustafadalga** [comment]
[bu](https://github.com/mustafadalga/Instagram-Bot/issues/9) ve [şu](https://github.com/mustafadalga/Instagram-Bot/issues/4) sorunları incelediniz mi ? Aynı sorunla karşılaşıyor olabilir misiniz ?
