### ISSUE TITLE
json.decoder.JSONDecodeError: 

### ISSUE THREAD

**Issue by altans10** [mustafadalga/Instagram-Bot#12]
Traceback (most recent call last):
  File "C:\Users\BT\instagram.py", line 2031, in <module>
    instagram = Instagram()
  File "C:\Users\BT\instagram.py", line 21, in __init__
    self.ayarlarYukle()
  File "C:\Users\BT\instagram.py", line 1040, in ayarlarYukle
    self.config = json.load(dosya)
  File "C:\Users\BT\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\BT\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\BT\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\BT\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 23 (char 87)

**Comment by mustafadalga** [comment]
Uygulama kurulumu için [gerekli adımları ](https://github.com/mustafadalga/Instagram-Bot/blob/master/Readme.tr.md#yap%C4%B1land%C4%B1rma-ayarlar%C4%B1)düzgün bir şekilde yaptınız mı ?

**Comment by altans10** [comment]
python 3.9 kurulu
selenium paketi kurulu
birde kodu denemeden önce sizin verdiğiniz kurulumu yaptım
python -m pip install -r .\requirements.txt
başka bişey yapmadım.

**Comment by mustafadalga** [comment]
`python -m pip install -r .\requirements.txt` komutunu çalıştırdığınzda paket kurulumları oldu mu ? 
` pip freeze ` komutunu çalıştırıp çıktısını paylaşır mısınız ?

**Comment by altans10** [comment]
C:\Users\BT>python -m pip install -r .\requirements.txt
Requirement already satisfied: selenium==3.141.0 in c:\users\bt\appdata\local\programs\python\python39\lib\site-packages (from -r .\requirements.txt (line 1)) (3.141.0)
Requirement already satisfied: termcolor==1.1.0 in c:\users\bt\appdata\local\programs\python\python39\lib\site-packages (from -r .\requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: colorama==0.3.9 in c:\users\bt\appdata\local\programs\python\python39\lib\site-packages (from -r .\requirements.txt (line 3)) (0.3.9)
Requirement already satisfied: requests==2.22.0 in c:\users\bt\appdata\local\programs\python\python39\lib\site-packages (from -r .\requirements.txt (line 4)) (2.22.0)
Requirement already satisfied: urllib3==1.25.3 in c:\users\bt\appdata\local\programs\python\python39\lib\site-packages (from -r .\requirements.txt (line 5)) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\bt\appdata\local\programs\python\python39\lib\site-packages (from requests==2.22.0->-r .\requirements.txt (line 4)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\bt\appdata\local\programs\python\python39\lib\site-packages (from requests==2.22.0->-r .\requirements.txt (line 4)) (2020.6.20)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\bt\appdata\local\programs\python\python39\lib\site-packages (from requests==2.22.0->-r .\requirements.txt (line 4)) (3.0.4)




C:\Users\BT>pip freeze
astroid==2.4.2
certifi==2020.6.20
chardet==3.0.4
colorama==0.3.9
idna==2.8
isort==5.5.4
lazy-object-proxy==1.4.3
mccabe==0.6.1
pylint==2.6.0
requests==2.22.0
selenium==3.141.0
six==1.15.0
termcolor==1.1.0
toml==0.10.1
urllib3==1.25.3
wrapt==1.12.1

**Comment by mustafadalga** [comment]
[config.json](https://github.com/mustafadalga/Instagram-Bot/blob/master/config.json) dosyasının yüklenmesi sırasında bir hata meydana gelmektedir. [config.json](https://github.com/mustafadalga/Instagram-Bot/blob/master/config.json) dosyasını düzgün bir şekilde indirdiğiniz mi.Dosya içerisindeki bir eksiklikten kaynaklı olabilir.

Kullandığınız python sürümü 3.9 olarak görünmektedir.Fakat 3.9 sürümü üzerinde test etmedim.3.8 sürümünü kurarak aynı işlemleri deneyebilirsiniz.

**Comment by altans10** [comment]
3.8 kurdum.
python -m pip install -r .\requirements.txt böyle 
C:\Users\BT>python instagram.py
python: can't open file 'instagram.py': [Errno 2] No such file or directory

şimdi paht sorunu var sanırım onu çözmeye çalışıyorum

**Comment by altans10** [comment]
sorunları tekrar kurulum yaparak düzelttim. Direk C:\Python\Python38 kurdum. 

C:\Users\BT>pip freeze
certifi==2020.6.20
chardet==3.0.4
colorama==0.4.4
idna==2.10
requests==2.24.0
selenium==3.141.0
termcolor==1.1.0
urllib3==1.25.10

C:\Users\BT>python instagram.py
python: can't open file 'instagram.py': [Errno 2] No such file or directory

**Comment by altans10** [comment]
3.8 kurdum ve sorunum devam ediyor. Java ile ilgili bir şey yüklenecek miydi? Onu yüklememiş olabilir miyim?


Traceback (most recent call last):
  File "instagram.py", line 2031, in <module>
    instagram = Instagram()
  File "instagram.py", line 21, in __init__
    self.ayarlarYukle()
  File "instagram.py", line 1040, in ayarlarYukle
    self.config = json.load(dosya)
  File "C:\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 23 (char 87)

**Comment by mustafadalga** [comment]
json dosyasının yüklenmesi esnasında  bir problem yaşanmaktadır.[bu](https://github.com/mustafadalga/Instagram-Bot/blob/master/config.json) dosya ile bilgisayarınızdaki config.json dosya aynı mı ? Çünkü repoyu yeniden indirip kurduğumda bir problem ile karşılaşmıyorum. (config.json dosyasının instagram.py ile aynı klasörde olması gerekiyor.)

Uygulamayı C:\Users\BT\ klasöründe çalıştırıyorsunuz görünüyor. Bi de uygulamayı direk C:\ dizinine kopyalayıp dener misiniz ?

**Comment by altans10** [comment]
Config ile instagram.py aynı dizinde. Python 3.8 tekrar kurduğumda c:\python\python38 dizinine kurdum. Çalıştırırkende c:\python\python38\insta>Python instagram.py şeklinde çalıştırıyorum
Tüm dosyalar insta klasörü içinde

**Comment by altans10** [comment]
en son aldığım hata bu şekilde.
C:\Python\Python38\ins>python instagram.py
Traceback (most recent call last):
  File "instagram.py", line 2031, in <module>
    instagram = Instagram()
  File "instagram.py", line 21, in __init__
    self.ayarlarYukle()
  File "instagram.py", line 1040, in ayarlarYukle
    self.config = json.load(dosya)
  File "C:\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 23 (char 87)

**Comment by altans10** [comment]
şuan botu çalıştırmayı başardım gibi. bi hesabın tüm gönderilerini beğen dediğimde böyle bir hata çıkıyor.
[-] An error occurred while liking balikesiraci's posts:Message: Unable to locate element: ul.k9GMp >li.Y8-fY >span >span.g47SY

**Comment by mustafadalga** [comment]
İnstagram web uygulamasının verileri javascript ile dinamik bir şekilde yüklenmektedir. İlgili html elemanları yüklenmeden seçmeye calıştığı için hatayı almaktasınız. İnternet yavaş olduğunda sayfa yavaş yüklenmektedir ve böyle hatalar olabilmektedir. Çözüm için config.json içerisinde yaptığınız işlemlerin süre aralıkları uzatabilirsiniz.

**Comment by altans10** [comment]
teşekkür ederim. Sorunlarımız çözüldü.

**Comment by mustafadalga** [comment]
Rica ederim,kolay gelsin.
