### ISSUE TITLE
after start, unable to find binary in default location

### ISSUE THREAD

**Issue by WhoR3born** [mustafadalga/Instagram-Bot#17]
[-] An error occurred during the browser initialization process:Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

https://i.vgy.me/CjZPG0.png

**Comment by mustafadalga** [comment]
hello, did you follow the steps for [installation](https://github.com/mustafadalga/Instagram-Bot#configuration-settings)?
