### ISSUE TITLE
Toplu gönderi ve takip sayısı silme özelliği eklensin 

### ISSUE THREAD

**Issue by emredkc23** [mustafadalga/Instagram-Bot#2]
Merhaba projenizi çok beğendim çok pratik sizden ricam sonraki versiyonda toplu gönderi silme ve toplu takipten çıkma özelliği

**Comment by mustafadalga** [comment]
Merhaba @emredkc23 ,
Yorumlarınız ve önerileriniz için teşekkür ederim.Önerilerinizi yapılacaklar listesine ekledim.
[Instagram Bot](https://github.com/mustafadalga/Instagram-Bot)'unun yeni versiyonu geliştirme aşamasındadır.

**Comment by mustafadalga** [comment]
Merhaba @emredkc23 ,
[Instagram Bot](https://github.com/mustafadalga/Instagram-Bot)'unun yeni versiyonu yayınlanmıştır.
