### ISSUE TITLE
logged in even when sign out happens successfully

### ISSUE THREAD

**Issue by anandxkumar** [mustafadalga/Instagram-Bot#23]
![Screenshot (272)](https://user-images.githubusercontent.com/44584067/103409707-036f5800-4b8e-11eb-9cd8-55334660a413.png)

Maybe the source code of Instagram has changed so maybe we need to change the code accordingly.

**Comment by mustafadalga** [comment]
An error that occurs as a result of updating the Instagram web application.
I updated the application. The problem has been fixed.
