### ISSUE TITLE
Unable to locate element: ul.k9GMp >li.Y8-fY >span >span.g47SY

### ISSUE THREAD

**Issue by fhrzx** [mustafadalga/Instagram-Bot#25]
Can you help me with my issue?
i got this "Unable to locate element: ul.k9GMp >li.Y8-fY >span >span.g47SY"
![image](https://user-images.githubusercontent.com/31997085/104314582-37426a00-550c-11eb-8cdc-fdf24085efc3.png)

**Comment by mustafadalga** [comment]
The reason it gives an error is that the page is processing before it loads. So your internet may be slow.

I tried. No error found.
![image](https://user-images.githubusercontent.com/25087769/104341928-5e4c6c00-550b-11eb-95aa-af5457c7248e.png)

**Comment by fhrzx** [comment]
**Solved** Nothing wrong with my connection. I just need to run the console as an administrator. Thanks.
