### ISSUE TITLE
Unable to locate element: a.-nal3 > span.g47SY

### ISSUE THREAD

**Issue by tunjayoff** [mustafadalga/Instagram-Bot#28]
Bir kullanıcının takipçilerini takip etme işlemi yaparken bu hatayı veriyor.

**Comment by mustafadalga** [comment]
Merhaba  test ettiğimde herhangi bir hata ile karşılaşmadım.Tekrardan dener misiniz ? 
![image](https://user-images.githubusercontent.com/25087769/107859676-1becb680-6e4c-11eb-9c25-a4c4255918f3.png)

**Comment by tunjayoff** [comment]
Python'ı ve gereklilikleri kaldırıp tekrar kurup kodu cmd değil de visual studio üzerinden çalıştırınca hata düzeldi. Sanırım kurulan paketlerde bir hata vardı ve  o yüzden bot hata veriyordu. Kodunuz bu alanda gördüğüm en iyi açık kaynak proje olabilir tebrik ederim.

> Merhaba test ettiğimde herhangi bir hata ile karşılaşmadım.Tekrardan dener misiniz ?
> ![image](https://user-images.githubusercontent.com/25087769/107859676-1becb680-6e4c-11eb-9c25-a4c4255918f3.png)

**Comment by mustafadalga** [comment]
> Python'ı ve gereklilikleri kaldırıp tekrar kurup kodu cmd değil de visual studio üzerinden çalıştırınca hata düzeldi. Sanırım kurulan paketlerde bir hata vardı ve o yüzden bot hata veriyordu. Kodunuz bu alanda gördüğüm en iyi açık kaynak proje olabilir tebrik ederim.
> 
> > Merhaba test ettiğimde herhangi bir hata ile karşılaşmadım.Tekrardan dener misiniz ?
> > ![image](https://user-images.githubusercontent.com/25087769/107859676-1becb680-6e4c-11eb-9c25-a4c4255918f3.png)

Cmd üzerinden çalıştırınca hata verebilir.Ben powershell kullanıyorum.Geri bildirim için teşekkür ederim :)
