### ISSUE TITLE
Config file is missing - Config dosyası eksik !

### ISSUE THREAD

**Issue by PauloRBalduin** [mustafadalga/Instagram-Bot#30]
Hi I'm new in the programming world, I was trying to run your code but I'm getting the error "Config file is missing - Config dosyası eksik !" the config file is in the same directory of the code, do you know what could be the issue?

**Comment by mustafadalga** [comment]
it should work if[ config.json](https://github.com/mustafadalga/Instagram-Bot/blob/master/config.json) file exists.
Maybe there is a problem with the terminal you are running.
Would you try it with powershell? There may be a problem with cmd.

**Comment by PauloRBalduin** [comment]
Hi , thanks for the answer, it was something wrong with my directories, because when I moved the files to other folder it worked. Good work thanks for share it !
