### ISSUE TITLE
login çalışmıyor

### ISSUE THREAD

**Issue by aspectsiz** [mustafadalga/Instagram-Bot#32]
![image](https://user-images.githubusercontent.com/81068489/111896505-2aba2080-8a2b-11eb-9cf1-f565a50b5281.png)

y

**Comment by mustafadalga** [comment]
kullanıcı adı ve parolayı doğru bir şekilde girdin mi ?

**Comment by aspectsiz** [comment]
Kullanıcı adı girdiğimde pass sormuyor hocam
Olduğu gibi kalıyor

**Comment by mustafadalga** [comment]
Evet, git üzerinden çalıştırılınca sorun var.cmder veya powershell kullanarak dener misiniz ? Git üzerinde kararlı çalışmadığını farkettim.

**Comment by aspectsiz** [comment]
Teşekkürlerimi ilettim git ile powershelin aynı görevi görebildiğini bilmiyordum.
Herşey düzgün çalışıyor gibi menü geldi

**Comment by mustafadalga** [comment]
> Teşekkürlerimi ilettim git ile powershelin aynı görevi görebildiğini bilmiyordum.
> Herşey düzgün çalışıyor gibi menü geldi

Rica ederim.
