### ISSUE TITLE
browser not initialize 

### ISSUE THREAD

**Issue by abhirajuneja** [mustafadalga/Instagram-Bot#4]
I face some error please solve my problem 
![instagram bot](https://user-images.githubusercontent.com/45552414/90304673-cc96ef00-ded7-11ea-8fbf-db1cc014603d.PNG)

**Comment by mustafadalga** [comment]
Hello @abhirajuneja ,
Have you defined the webdriver path in  [config.json](https://github.com/mustafadalga/Instagram-Bot/blob/88396d3a2e94a6b274c228fb0912d720e6674d30/config.json#L3) ?
Default webdriver path `C:\\geckodriver.exe`
Set the driver path.

**Comment by abhirajuneja** [comment]
I am already set the path in the config.json but the problem is still

**Comment by mustafadalga** [comment]
Does the browser open?  Do you see the browser start up?

Can you share driver_path value?

**Comment by abhirajuneja** [comment]
No Browser Not Startup and my driver Path value is C:\\gecodriver.exe

**Comment by mustafadalga** [comment]
1.Change driver_path value to `C:\\geckodriver.exe`
2.Move geckodriver.exe to `C:\\`
