### ISSUE TITLE
  File "instagram.py", line 276 SyntaxError: Non-ASCII character '\xc4' in file instagram.py on line 276, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

### ISSUE THREAD

**Issue by Knoples** [mustafadalga/Instagram-Bot#8]
Bu işlerde yeniyim bu hatayı aldım zahmet olmazsa yardım edebilir misin? Ne yapmam gerekiyor?
![Screenshot 2020-09-14 14:31:50](https://user-images.githubusercontent.com/71286690/93124100-1f122980-f697-11ea-827d-2132dfa158ad.png)

**Comment by mustafadalga** [comment]
Merhaba @Knoples ,
Scriptin en başına aşağıdaki satırı ekleyip dener misiniz ?

`# -*- coding: utf-8 -*-`

**Comment by Knoples** [comment]
![Screenshot 2020-09-14 14:31:50](https://user-images.githubusercontent.com/71286690/93130358-6cdf5f80-f6a0-11ea-804c-fc0c2859cd83.png)

**Comment by Knoples** [comment]
![Screenshot 2020-09-14 15:39:49](https://user-images.githubusercontent.com/71286690/93130458-8e404b80-f6a0-11ea-933e-31fb29456ac1.png)
Bu şekilde değil herhalde  biraz kötüyüm kusura bakmayın yanlış bir şey yapmış olabilirim

**Comment by mustafadalga** [comment]
instagram.py dosyasının içerisine , ilk satıra kodu ekleyip tekrar deneyiniz.

**Comment by Knoples** [comment]
oldu çok teşekkürler adamsın

**Comment by mustafadalga** [comment]
Rica ederim , kolay gelsin.

**Comment by Knoples** [comment]
teşekkürler
