### ISSUE TITLE
Açmakta zorluk çekiyorum

### ISSUE THREAD

**Issue by hasansezertasan** [mustafadalga/Instagram-Bot#9]
Merhabalar, ben bu uygulamanın kullanılmasında zorluk çekiyorum. Mozillayı indirdim ama yine de açamadım. Yardımcı olma imkanınız var mı? Bir video tutorial hazırlayabilirseniz çok sevinirim.

**Comment by mustafadalga** [comment]
Merhaba , uygulamanın nasıl kurulacağı ve kullanılacağı hakkında doküman içerisinde adım adım anlatılmıştır. Lütfen doküman [inceleyin](https://github.com/mustafadalga/Instagram-Bot/blob/master/Readme.tr.md#yap%C4%B1land%C4%B1rma-ayarlar%C4%B1).

**Comment by hasansezertasan** [comment]
Ben o adımların hepsini yaptım windows kullanıyorum. Bilgisayarımda python kurulu, instagram.py tıkladığımda da terminal açılıp hemen kapanıyor.
![image](https://user-images.githubusercontent.com/13135006/94338152-c7f64800-fff8-11ea-96f9-375077709943.png)

**Comment by mustafadalga** [comment]
Uygulamanın olduğu klasörde terminalinizi açıp aşağıdaki komutu çalıştırınız.

```
python instagram.py
```

**driver_path** düzgün ayarlandığından emin olun.Veya  geckodriver.exe dosyasını C:\\ dizinine kopyalayıp **driver_path**'i aşağıdaki gibi yapılandırabilirsiniz.Belirttiğiniz konum adresinde türkçe karakter olmamasına dikkat etmelisiniz.

```
C:\\geckodriver.exe
```

**Comment by hasansezertasan** [comment]
![image](https://user-images.githubusercontent.com/13135006/94341110-9e94e680-000f-11eb-9c58-e00da9c2a066.png)
![image](https://user-images.githubusercontent.com/13135006/94341120-abb1d580-000f-11eb-9df7-7c3294d1afe0.png)
Birinci görselde ki ekranı alıyorum veya işlemini gerçekleştirdim, herhangi bir Türkçe karakter olma durumu da yok.

**Comment by mustafadalga** [comment]
[Python](https://programcigenc.wordpress.com/2016/05/03/pythoni-yola-eklemek-windows/)'u Windows path'lere ekleyin ve uygulama gerekliliklerini de kurarak tekrar deneyin. Bu sorun [script](https://github.com/mustafadalga/Instagram-Bot) ile ilgili değildir. Python yapılandırılmanız ile ilgilidir.

**Comment by vimevim** [comment]
Pythonu tekrar kurdum ve denedim bu sefer kurulumda "py dosyalarını açmaya izin ver" gibi bir kısım vardı seçili değildi orayı da seçtim ancak gene olmadı. Ne yapmamı önerirsiniz.

**Comment by hasansezertasan** [comment]
![image](https://user-images.githubusercontent.com/13135006/94346766-7caf5a00-0037-11eb-9db4-6e881498fdbc.png)
Dediğiniz işlemleri yaptım, windows pathlere ekleme sayfasında da denememi yaptım ">>>" ifadelerini gördüm yani başarılı ekledim ama yine de bu sonuçla karşı karşıyayım.

20:56 editi: 
![image](https://user-images.githubusercontent.com/13135006/94347184-c8afce00-003a-11eb-95dd-af47c1687b28.png) selenium kurmam gerekiyormuş sanırım onu da kurdum ama bu hatayı alıyorum şimdi.

**Comment by mustafadalga** [comment]
Bu proje içerisinde görmüş olduğunuz gibi [requirements.txt](https://github.com/mustafadalga/Instagram-Bot/blob/master/requirements.txt) bulunmaktadır.Bu gereklilikleri kurmadan script'i kullanamazsınız.

Paket kurulumları için aşağıdaki gibi bir komutu kullanabilirsiniz.
```
python -m pip install -r .\requirements.txt
```

**Comment by hasansezertasan** [comment]
![image](https://user-images.githubusercontent.com/13135006/94363933-6ef8e380-00ce-11eb-8887-c76b21e74b91.png)
Bu yaptığım işlemleri yapmayı bilmeyen birisi için faydalı bir issue olmuştur umarım değerli vaktinizi bana ayırıp yardımcı olduğunuz için çok teşekkür ediyorum.

**Comment by mustafadalga** [comment]
Rica ederim , kolay gelsin.

**Comment by kgdsa** [comment]
Mustafa Bey aynı sorun evet deneyip size tekrar geri dönüş yapıcam.Çok teşekkür ederim.
